### PR TITLE
Use helpers to get correct information (especially when HA is used)

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by vuntz** [comment]
IIRC, @ovisan mentioned that this created an issue because of the pacemaker cookbook failing on windows in the initialization step. @aspiers was this fixed?

**Comment by aspiers** [comment]
@vuntz I don't think so - I can only remember us discussing on IRC:

```
2014-12-19 13:49:40     ovisan  vuntz: http://pastie.org/private/drcbwychuyg2knf7ytj0aw this is the output when applying the cookbook from rpm
2014-12-19 13:56:21     vuntz   ovisan: ah, interesting stuff. Was not expected at all, but kind of makes sense
2014-12-19 13:57:18     vuntz   aspiers: see ovisan's link above. Any good idea to still keep this fixme while not crashing when the cookbook comes because it's a dep of another cookbook?
2014-12-19 13:58:06     aspiers segfault (ENOCONTEXT)
2014-12-19 13:58:37     aspiers oh
2014-12-19 13:59:29     aspiers we could move the check into the recipes?
2014-12-19 14:04:04     vuntz   aspiers: works for me
2014-12-19 14:04:16     aspiers but how to avoid checking multiple times?
2014-12-19 14:04:22     aspiers could check in a library
2014-12-19 14:04:28     aspiers and mark an attribute when checked
2014-12-19 14:04:47      *      vuntz is in a call again
2014-12-19 14:04:58     vuntz   so will come back to it afterwards
2014-12-19 14:05:26     vuntz   ovisan: you can just remove this "fatal!" line in the pacemaker barclamp for now
```

**Comment by dirkmueller** [comment]
+1, assuming that it works

**Comment by vuntz** [comment]
I created https://github.com/crowbar/barclamp-pacemaker/pull/163 for the fatal error that we hit on windows.

**Comment by jsuchome** [comment]
+1

**Comment by ovisan** [comment]
+1 tested and works

**Pull request merged**
