### PR TITLE
Support for ceilometer-compute-agent on HyperV nodes [backport]

### PR DESCRIPTION
**Pull request by jsuchome**
Cherry-picked commits from https://github.com/crowbar/barclamp-hyperv-compute/pull/32 for tex

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
Please use `cherry-pick -x` when backporting (to have a mention of the old commit in the log message).

**Comment by tboerger** [comment]
```cherry-pick -x```, afterwards +1

**Comment by nkrinner** [comment]
https://github.com/crowbar/barclamp-hyperv-compute/pull/34

I can't close this pr.

**Pull request closed without merging**
